name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.1
        with:
          channel: github-actions
          status: STARTING
          color: warning

      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Publish to RubyGems
          run: |
            mkdir -p $HOME/.gem
            touch $HOME/.gem/credentials
            chmod 0600 $HOME/.gem/credentials
            printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
            gem build *.gemspec
            gem push *.gem
          env:
            GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: FAILED
          color: danger